name: Releases

on: 
  push:
    tags:
    - '*'

jobs:                
    build:
        uses: ./.github/workflows/main.yml
    release:
        runs-on: ubuntu-latest
        needs: build
        if: startsWith(github.ref, 'refs/tags/')
        steps:
            - name: checkout repo
              uses: actions/checkout@v4

            - name: pull artifacts from previous build step
              uses: actions/download-artifact@v4
              with:
                path: release-pdfs
                merge-multiple: True

            - name: list artifacts
              id: ls_release_pdfs
              run: ls -l release-pdfs/*.pdf

            - name: Create Release
              id: create_release
              uses: softprops/action-gh-release@v2
              with:
                files: |
                  release-pdfs/*.pdf
