name: Releases

on: 
  push:
    tags:
    - '*'

jobs:                
    build:
        uses: ./.github/workflows/main.yml
    release:
        runs-on: ubuntu-latest
        needs: build
        if: startsWith(github.ref, 'refs/tags/')
        steps:
            - name: checkout repo
              uses: actions/checkout@v4

            - name: pull artifacts from previous build step
              uses: actions/download-artifact@v4
              with:
                path: tex
                merge-multiple: True

            - name: list artifacts
              run: ls -l tex/*.pdf

            - name: Create Release
              id: create_release
              uses: actions/create-release@v1
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                tag_name: ${{ github.ref }}
                release_name: Release ${{ github.ref }}
                draft: false
                prerelease: false

            - name: Upload Release Asset slide-N
              uses: actions/upload-release-asset@v1
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                upload_url: ${{ steps.create_release.outputs.upload_url }}
                asset_path: tex/slide-N.pdf
                asset_name: slide-N.pdf
                asset_content_type: application/pdf

            - name: Upload Release Asset slide-E
              uses: actions/upload-release-asset@v1
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                upload_url: ${{ steps.create_release.outputs.upload_url }}
                asset_path: tex/slide-E.pdf
                asset_name: slide-E.pdf
                asset_content_type: application/pdf

            - name: Upload Release Asset slide-NE
              uses: actions/upload-release-asset@v1
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                upload_url: ${{ steps.create_release.outputs.upload_url }}
                asset_path: tex/slide-NE.pdf
                asset_name: slide-NE.pdf
                asset_content_type: application/pdf
